name: Lint check

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup C++
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake clang clang-tidy
      - name: Build compile_commands.json
        run: cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Add problem matcher
        run: echo "::add-matcher::.github/clang-tidy-problem-matcher.json"
      - name: Run clang-tidy
        continue-on-error: true
        run: run-clang-tidy -p build -header-filter=.*
      - name: Remove problem matcher
        run: echo "::remove-matcher owner=clang-tidy::"
